name: dasegan
channels:
  - pytorch
  - nvidia
dependencies:
  - pytorch==1.7.0 
  - torchvision==0.8.0
  - torchaudio==0.7.0
  - cudatoolkit=11.0
  - python=3.8  # You can adjust the Python version if needed
  - pip
  - pip:
    - numpy==1.23.1 #avoid medpy np.bool error
    - scipy
    - pandas
    - nibabel
    - albumentations
    - scikit-learn
    - scikit-image
    - slackclient
    - pytorchcv
    - matplotlib
    - opencv-python
    - monai
    - Pillow
    - tqdm
    - pydicom
    - requests
    - seaborn
    - medpy
    - pretty_errors
    - wandb